#include <stdlib.h>
#include <numeric>
#include "TObjString.h"
#include "Riostream.h"
#include "TString.h"
#include "TRegexp.h"
#include "TSystem.h"
#include "TFile.h"
#include "TLegend.h"
#include "TPaveText.h"
#include "TPaveStats.h"
#include "TText.h"
#include "TF1.h"
#include "TF3.h"
#include "TH1D.h"
#include "TH2D.h"
#include "TProfile.h"
#include "TStyle.h"
#include "TROOT.h"
#include "TTree.h"
#include "TNtuple.h"
#include "TVectorD.h"
#include "TGraph.h"
#include "TGraphErrors.h"
#include "TGraphAsymmErrors.h"
#include "TRandom3.h"
#include "TCanvas.h"
#include "TAxis.h"
#include "TMath.h"
#include "TLine.h"
#include "TComplex.h"
#include "TF1Convolution.h"
#include "TVirtualFFT.h"
#include "TVirtualFitter.h"
#include "RooDataSet.h"
#include "RooRealVar.h"
#include "TFitResultPtr.h"
#include "TMatrixDSym.h"
#include "TFitResult.h"
#include "Fit/FitResult.h"
#include "Math/Interpolator.h"
#include <sys/stat.h>
#include <unistd.h>
#include <string>
#include <fstream>
#include <tuple>

#include "Riostream.h"
#include <TSystemDirectory.h>
#include <TList.h>

using namespace std;
